package coredevices.pebble.signal

import kotlinx.serialization.json.*
import kotlin.test.*

class SignalWireTest {
    private val received = 1_789_000_000_000L
    @Test fun cNumericObjectAndNullValuesRoundTripWithoutInventingHeartRateAge() {
        val payload = Json.parseToJsonElement("""[
            {"key":"health.steps","source":"watch","value":42,"unit":"steps","collectedAt":1,"period":"today","status":"fresh"},
            {"key":"watch.motion","source":"watch","value":{"samples":100,"rms":0.12},"unit":"g","collectedAt":1,"period":"5_second_sample","status":"fresh"},
            {"key":"health.heart_rate","source":"watch","value":null,"collectedAt":1,"measuredAt":1789000000000,"status":"timestamp_unknown"}
        ]""")
        val rows = assertNotNull(SignalWire.observations(payload, received))
        assertEquals("42", rows[0].value)
        assertEquals("{\"samples\":100,\"rms\":0.12}", rows[1].value)
        assertEquals("", rows[2].value)
        assertNull(rows[2].measuredAt)
        assertTrue(rows.all { it.collectedAt == received })
        val keys = rows.map { it.key }.toSet()
        assertTrue(rows.all { SignalWatchValidation.validate(it, keys, keys, received) != null })
    }
    @Test fun actualCSerializedSnapshotIsAccepted() {
        // Captured from pebble-field-inspector/tests/fixtures/watch-observations.json.
        val payload = Json.parseToJsonElement("""{
  "request_id": 45,
  "observations": [
    {
      "key": "health.steps",
      "source": "watch",
      "value": 4321,
      "unit": "steps",
      "collectedAt": 1788886800000,
      "status": "fresh",
      "period": "today",
      "measuredAt": 1788886800000,
      "windowStart": 1788850800000,
      "windowEnd": 1788886800000,
      "date": "2026-09-08"
    },
    {
      "key": "health.restful_sleep",
      "source": "watch",
      "value": null,
      "unit": "seconds",
      "collectedAt": 1788886800000,
      "status": "permission_denied",
      "period": "day",
      "measuredAt": 1788850800000,
      "windowStart": 1788764400000,
      "windowEnd": 1788850800000,
      "date": "2026-09-07"
    },
    {
      "key": "watch.motion",
      "source": "watch",
      "value": {
        "samples": 50,
        "mean_x": 20,
        "mean_y": -30,
        "mean_z": 998,
        "peak_abs_axis": 1200
      },
      "unit": "mg",
      "collectedAt": 1788886800000,
      "status": "fresh",
      "period": "5_second_sample",
      "measuredAt": 1788886805000,
      "windowStart": 1788886800000,
      "windowEnd": 1788886805000
    },
    {
      "key": "health.heart_rate",
      "source": "watch",
      "value": 72,
      "unit": "bpm",
      "collectedAt": 1788886800000,
      "status": "timestamp_unknown",
      "period": "current"
    }
  ],
  "complete": true
}""").jsonObject
        val at = 1788886805000L
        val rows = assertNotNull(SignalWire.observations(payload.getValue("observations"), at))
        val keys = rows.map { it.key }.toSet()
        assertEquals("4321", rows[0].value)
        assertEquals("", rows[1].value)
        assertEquals("permission_denied", rows[1].status)
        assertTrue(rows[2].value.contains("peak_abs_axis"))
        assertEquals("72", rows[3].value)
        assertNull(rows[3].measuredAt)
        assertNull(rows[3].windowStart)
        assertTrue(rows.all { SignalWatchValidation.validate(it, keys, keys, at) != null })
    }
    @Test fun actualCSerializedMinuteHistoryPreservesTheReturnedWindow() {
        // Generated by pebble-field-inspector/tests/collection-contract.test.py.
        val payload = Json.parseToJsonElement("""[
          {"key":"watch.minute_history","source":"watch","value":{"schema":1,"requested_minutes":15,"returned_minutes":3,"valid_minutes":2,"requested_start_ms":1789343100000,"requested_end_ms":1789344000000,"columns":["steps","vmc","orientation","light","heart_rate_bpm"],"minutes":[[0,0,0,null,null],null,[3,300,16,4,72]]},"unit":"minute_records","collectedAt":1789344037000,"status":"available","period":"recent_15_minutes","windowStart":1789343580000,"windowEnd":1789343760000,"measuredAt":1789343760000}
        ]""")
        val at = 1_789_344_038_000L
        val reading = assertNotNull(SignalWire.observations(payload, at)).single()
        val enabled = setOf(SignalWatchHistory.KEY)
        val result = assertNotNull(SignalWatchValidation.validate(reading, enabled, enabled, at))
        assertEquals(at, result.collectedAt)
        assertEquals(1_789_343_580_000L, result.windowStart)
        assertEquals(1_789_343_760_000L, result.windowEnd)
        assertEquals(result.windowEnd, result.measuredAt)
        val history = assertNotNull(SignalWatchHistory.parse(result))
        assertEquals(3, history.minutes.size)
        assertEquals(2, history.validMinutes)
        assertEquals(SignalWatchMinute(0, 0, 0, null, null), history.minutes[0])
        assertNull(history.minutes[1])
        assertEquals(SignalWatchMinute(3, 300, 16, 4, 72), history.minutes[2])
        assertNull(SignalWatchValidation.validate(reading, setOf("watch.motion"), enabled, at))
    }

    @Test fun actualCClippedHistoryRetainsCompletedMinutesAndSdkProvenance() {
        // Production C serializer, qemu_tail regression case; all readings are synthetic.
        val payload = Json.parseToJsonElement("""[{"key":"watch.minute_history","source":"watch","value":{"schema":1,"requested_minutes":15,"returned_minutes":10,"valid_minutes":10,"requested_start_ms":1789343100000,"requested_end_ms":1789344000000,"columns":["steps","vmc","orientation","light","heart_rate_bpm"],"minutes":[[255,65535,255,4,255],[255,65535,255,4,255],[255,65535,255,4,255],[255,65535,255,4,255],[255,65535,255,4,255],[255,65535,255,4,255],[255,65535,255,4,255],[255,65535,255,4,255],[255,65535,255,4,255],[255,65535,255,4,255]]},"unit":"minute_records","collectedAt":1789344037000,"status":"available","period":"recent_15_minutes","windowStart":1789343400000,"windowEnd":1789344000000,"measuredAt":1789344000000,"fields":{"reason":"history_window_clipped","sdk_returned_minutes":"11","sdk_window_start_s":"1789343400","sdk_window_end_s":"1789344060","excluded_after_requested_minutes":"1"}}]""")
        val at = 1_789_344_038_000L
        val keys = setOf(SignalWatchHistory.KEY)
        val wire = assertNotNull(SignalWire.observations(payload, at)).single()
        val result = assertNotNull(SignalWatchValidation.validate(wire, keys, keys, at))
        val history = assertNotNull(SignalWatchHistory.parse(result))
        assertEquals(10, history.minutes.size)
        assertEquals(10, history.validMinutes)
        assertEquals(1_789_344_000_000L, result.windowEnd)
        assertEquals(result.windowEnd, result.measuredAt)
        assertEquals("history_window_clipped", result.fields["reason"])
        assertEquals("11", result.fields["sdk_returned_minutes"])
        assertEquals("1", result.fields["excluded_after_requested_minutes"])
        assertContains(assertNotNull(SignalWatchHistory.describe(result)), "5 missing")
    }

    @Test fun actualCEmptyInvalidAndMotionOutputsRetainTheirTimingMeaning() {
        val fixtures = listOf(
            """[{"key":"watch.motion","source":"watch","value":{"samples":2,"mean_x":0,"mean_y":0,"mean_z":1000,"peak_abs_axis":1000,"variance_mg2":250000,"received_samples":6,"vibration_excluded":1,"timestamp_rejected":3,"capacity_excluded":0,"first_sample_ms":1789344037025,"last_sample_ms":1789344037125,"requested_hz":10,"requested_duration_ms":5000,"timing":"sdk_epoch_ms"},"unit":"mg","collectedAt":1789344037000,"status":"fresh","period":"5_second_sample","windowStart":1789344037025,"windowEnd":1789344037125,"measuredAt":1789344037125}]""",
            """[{"key":"watch.minute_history","source":"watch","value":{"schema":1,"requested_minutes":15,"returned_minutes":3,"valid_minutes":0,"requested_start_ms":1789343100000,"requested_end_ms":1789344000000,"columns":["steps","vmc","orientation","light","heart_rate_bpm"],"minutes":[null,null,null]},"unit":"minute_records","collectedAt":1789344037000,"status":"unavailable","period":"recent_15_minutes","windowStart":1789343580000,"windowEnd":1789343760000}]""",
            """[{"key":"watch.minute_history","source":"watch","value":{"schema":1,"requested_minutes":15,"returned_minutes":0,"valid_minutes":0,"requested_start_ms":1789343100000,"requested_end_ms":1789344000000,"columns":["steps","vmc","orientation","light","heart_rate_bpm"],"minutes":[]},"unit":"minute_records","collectedAt":1789344037000,"status":"unavailable","period":"recent_15_minutes"}]""",
        )
        val at = 1_789_344_038_000L
        val keys = setOf("watch.motion", SignalWatchHistory.KEY)
        val rows = fixtures.map { fixture ->
            val reading = assertNotNull(SignalWire.observations(Json.parseToJsonElement(fixture), at)).single()
            assertNotNull(SignalWatchValidation.validate(reading, keys, keys, at))
        }
        assertEquals(1_789_344_037_025L, rows[0].windowStart)
        assertEquals(1_789_344_037_125L, rows[0].measuredAt)
        assertContains(assertNotNull(signalWatchMotionDescription(rows[0])), "2 accepted samples of 6 received")
        assertContains(assertNotNull(signalWatchMotionDescription(rows[0])), "100 ms")
        assertEquals(1_789_343_580_000L, rows[1].windowStart)
        assertEquals(1_789_343_760_000L, rows[1].windowEnd)
        assertNull(rows[1].measuredAt)
        assertNull(rows[2].windowStart); assertNull(rows[2].windowEnd); assertNull(rows[2].measuredAt)
        assertTrue(rows.drop(1).all { it.status == "unavailable" })
    }

    @Test fun malformedAndOversizedBatchesAreRejected() {
        assertNull(SignalWire.observations(Json.parseToJsonElement("{}"), received))
        assertNull(SignalWire.observations(Json.parseToJsonElement("[null]"), received))
        assertNull(SignalWire.observations(Json.parseToJsonElement("[{}]"), received))
        assertNull(SignalWire.observations(Json.parseToJsonElement("[" + List(13) { "{}" }.joinToString() + "]"), received))
    }
}
